# Generated by Django 5.0 on 2024-03-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_featured_product_collection_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='products',
            new_name='featured_product',
        ),
    ]
