# Generated by Django 5.0 on 2023-12-10 07:54

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(db_default=models.Value(True)),
        ),
    ]
