# Generated by Django 5.0 on 2023-12-10 08:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0002_alter_article_created_alter_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='character_count',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Length('body'), output_field=models.IntegerField()),
        ),
    ]
